# Generated by Django 2.0.2 on 2019-06-19 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postcard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='NO Comment!'),
            preserve_default=False,
        ),
    ]
